### ISSUE TITLE
展示页面问题

### ISSUE THREAD

**Issue by 2501224066** [dcalsky/zzkia#2]
你展示页面用的幻灯片插件，高度超过一屏了，底下的github图标现在在图片中间

**Comment by dcalsky** [comment]
Thanks for your reminding, I will fix it soon.

**Comment by 2501224066** [comment]
你的问题为啥要我修复，老铁？？？

**Comment by dcalsky** [comment]
> 你的问题为啥要我修复，老铁？？？

Sorry for typo.

**Comment by 2501224066** [comment]
我之前也做个一个差不多的
![img](https://img.hacpai.com/file/2019/07/TIM%E5%9B%BE%E7%89%8720190719111314-78b1f0ed.jpg)
给图片加上中文加翻译字幕
